title: Junzhe Ma
# Comment out url when working locally to resolve base urls correctly
url: https://bcglacier.github.io

# Default social-share preview image (Open Graph / Twitter card). Lives in /images/.
og_image: og.jpg

# Owner/author information
owner:
  name: Junzhe Ma
  avatar: avatar.jpg
  email: bcglacier_1@qq.com
  github: bcglacier
  linkedin: 
  scholar: 
  researchgate: 

# https://search.google.com/search-console/ownership
google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# Links to include in top navigation
links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Beyond Research
    url: /hobbies/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai
future: true
highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
